language: php
php:
    - "5.3"
branches:
    only:
        - master
before_script: GHTOKEN= sudo apt-get install doxygen graphviz make
script: GHTOKEN= make all
after_success: build/travis-publish.sh
env:
    global:
        secure: "clhWnnHTsGgpaUBAkAz8Rf/b2Qd70EO49vfA4RbX6ySEb78GqKayrEFEi1bIxWMhmahbPr8UZcZDLw2svbLq63OLlHVoVwRGhADzKku5SUTrouA8Qnynb8SJ61821CR27arHGEgxhR2b0dKpBCWrFnsNfmyrDRJol/0/nt089Co="
