language: php
php:
    - "5.3"
branches:
    only:
        - master
script: GHTOKEN= make all
after_success: build/travis-publish.sh
env:
    global:
        secure: "RgJfQTxHt5fu6C7f+R4IgPzMxMRFEQPIWj/qcKM8yCVr3mPWU5iOkGs3g5WHT9VDuBhjIRnv0BWFwXARmtgr55Wb07oxyKLYfRC47KPnWhPw0hP/ypQ4/W4h5LCAiJpAKjubpROJZvdWZfX4RndAZXrvdtXy3PX6Yxcdo8zXdwc="
